<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'http://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '256M');




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db5470035476');
define('DB_USER', 'fw0988905448');
define('DB_PASSWORD', 'iWFymtlXfFI6ybaZSIARwZwasCwLtP');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'wp_fja801fqar_';


/****************************************************************************/
/*                          Plugin Configuration                            */
/****************************************************************************/




/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          '@AT%VtLdDGvO7ZaQ2sP:L<NA]pJs(76/zk]`Q4P.*gS4$H:eO0WB{zZq:QY])Yvd');
define('SECURE_AUTH_KEY',   'M~f)ivuwF5{Lx.hHa%C!`Oc{7>MXJ$030%lE4CMS28cAYj$Lw8{:mo!p+8`8pt,A');
define('LOGGED_IN_KEY',     'PU=M1akX*fFj*6Czgv|(?b-rGkp`PL-Pq^[:CTV};gAhbc*4b!In50$oAi*+}9rD');
define('NONCE_KEY',         'E;2DFxMff/l#X-Qb6MVt*%!5nHw]y={X$}W}giuj8Hxd-JTUI/.!}A|Zx3YfrqY/');
define('AUTH_SALT',         'usdpcOX[I%A9?YXcjlDI~j>{/;x-syrG`1<SfE3ce;Qk0q,i&$RupIM9[eN7EcrD');
define('SECURE_AUTH_SALT',  'Ap9{q4reUCcMh_/h!~5rwmNqHuq9E;[e02EbFa(,7vXC`[o)9zU~+N$V)j$YN`9j');
define('LOGGED_IN_SALT',    '.NvA~@Smzb+b{;y+R@m^;k$T_Rj$kx~f0jAr#t&pJ5;*8oWMlQ7B.o>4_O`uOhKP');
define('NONCE_SALT',        'LD>YeZ$or2C@gRelE>#[azwz;]5RTHjRL_,tI-Y(&!S%E{i(K#=![dR(8IMrwl+V');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);
define('WP_DEBUG_LOG', false);


/****************************************************************************/
/*                              Custom Content                              */
/****************************************************************************/



/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
